# Generated by Django 4.0.2 on 2022-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='imageUrl',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='song',
            name='imageUrl',
            field=models.CharField(max_length=1500),
        ),
    ]
